- name: Set RustDesk Password in Config
  run: |
    $configPath = "$env:APPDATA\RustDesk\config\RustDesk.toml"
    $password = "GitHubActions123!"
    $content = @"
[global]
password = '$password'
"@
    New-Item -ItemType Directory -Force -Path (Split-Path $configPath) | Out-Null
    $content | Out-File -FilePath $configPath -Encoding UTF8
    Write-Host "RustDesk password written to config file."
