name: Windows - RustDesk ID Retrieval (Run Only)
on:
  workflow_dispatch:

jobs:
  rustdesk_id_retrieval:
    name: RustDesk starten und ID abrufen
    runs-on: windows-latest

    steps:
      - name: RustDesk herunterladen
        id: download_rustdesk_step
        run: |
          Write-Host "Starte RustDesk-Einrichtung..."
          Write-Host "Lade RustDesk-Anwendung von der angegebenen URL herunter..."
          
          $rustDeskDownloadUrl = "https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.exe"
          $downloadPath = "$env:TEMP\rustdesk-portable.exe"

          try {
              Invoke-WebRequest -Uri $rustDeskDownloadUrl -OutFile $downloadPath -ErrorAction Stop
              Write-Host "RustDesk-Anwendung erfolgreich heruntergeladen nach $downloadPath"
          } catch {
              Write-Error "Fehler beim Herunterladen der RustDesk-Anwendung von '$rustDeskDownloadUrl': $($_.Exception.Message)"
              # Setze Output auch bei Fehler
              "rustdesk_exe_path=" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              "download_success=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              exit 1
          }

          # Stelle sicher, dass die heruntergeladene Datei existiert
          if (-not (Test-Path $downloadPath)) {
              Write-Error "FEHLER: Heruntergeladene RustDesk-Anwendung nicht gefunden unter $downloadPath."
              "rustdesk_exe_path=" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              "download_success=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              exit 1
          }
          
          Write-Host "Heruntergeladene RustDesk-Anwendung verifiziert."
          # Verwende die korrekte Syntax für GitHub Actions Outputs
          "rustdesk_exe_path=$downloadPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "download_success=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: RustDesk starten und ID abrufen
        # Führe diesen Step nur aus, wenn der Download erfolgreich war
        if: steps.download_rustdesk_step.outputs.download_success == 'true'
        run: |
          # Verwende eine robustere Methode, um den Pfad zu erhalten
          $rustDeskExePath = "${{ steps.download_rustdesk_step.outputs.rustdesk_exe_path }}"
          
          # Zusätzliche Validierung
          if ([string]::IsNullOrEmpty($rustDeskExePath) -or -not (Test-Path $rustDeskExePath)) {
              Write-Error "Fehler: RustDesk-Anwendungspfad '$rustDeskExePath' nicht verfügbar oder Datei existiert nicht."
              "rustdesk_id=DOWNLOAD_FAILED_NO_EXE" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              exit 1
          }

          Write-Host "--- Starte RustDesk-Anwendung direkt und versuche ID abzurufen ---"
          Write-Host "Verwende RustDesk-Pfad: $rustDeskExePath"

          # Starte RustDesk im Hintergrund
          Write-Host "Starte RustDesk-Anwendung im Hintergrund: '$rustDeskExePath --no-daemon'..."
          try {
              $process = Start-Process -FilePath $rustDeskExePath -ArgumentList "--no-daemon" -WindowStyle Hidden -PassThru -ErrorAction Stop
              Write-Host "RustDesk-Hintergrundprozess gestartet (PID: $($process.Id)). Warte 20 Sekunden, damit die ID generiert wird..."
              Start-Sleep -Seconds 20
              Write-Host "Wartezeit für ID-Generierung beendet."
          } catch {
              Write-Warning "Konnte RustDesk-Hintergrundprozess nicht starten: $($_.Exception.Message). Versuche trotzdem ID abzurufen."
          }

          # Versuche, die ID mit --get-id abzurufen
          $rustDeskId = $null
          Write-Host "Versuche, RustDesk ID mit '$rustDeskExePath --get-id' abzurufen..."
          try {
              $psi = New-Object System.Diagnostics.ProcessStartInfo
              $psi.FileName = $rustDeskExePath
              $psi.Arguments = "--get-id"
              $psi.RedirectStandardOutput = $true
              $psi.RedirectStandardError = $true
              $psi.UseShellExecute = $false
              $psi.CreateNoWindow = $true

              $idProcess = New-Object System.Diagnostics.Process
              $idProcess.StartInfo = $psi
              $idProcess.Start() | Out-Null
              
              $timeout = $idProcess.WaitForExit(15000) # 15 Sekunden Timeout
              
              if ($timeout) {
                  $idOutput = $idProcess.StandardOutput.ReadToEnd().Trim()
                  $idError = $idProcess.StandardError.ReadToEnd().Trim()
                  Write-Host "Befehl '$rustDeskExePath --get-id' beendet mit Exit Code: $($idProcess.ExitCode)"
                  Write-Host "Standard-Ausgabe (STDOUT): '$idOutput'"
                  if ($idError) { Write-Host "Standard-Fehler (STDERR): '$idError'" }

                  # Suche nach einer 9-stelligen ID in der Ausgabe
                  if ($idOutput -match "(\d{9})") {
                      $rustDeskId = $Matches[1]
                      Write-Host "RustDesk ID erfolgreich über --get-id gefunden: $rustDeskId"
                  } else {
                      Write-Warning "Keine 9-stellige ID in der --get-id-Ausgabe gefunden. Ausgabe war: '$idOutput'"
                  }
              } else {
                  Write-Error "RustDesk --get-id-Prozess hat nach 15 Sekunden ein Timeout."
                  $idProcess.Kill()
              }
          } catch {
              Write-Error "Fehler beim Ausführen von RustDesk --get-id: $($_.Exception.Message)"
          }

          # Fallback: Versuche, die ID aus der Konfigurationsdatei zu lesen
          if (-not $rustDeskId) {
              Write-Host "--- RustDesk ID nicht über --get-id gefunden. Versuche, aus Konfigurationsdateien zu lesen ---"
              $rustDeskConfigPaths = @(
                  (Join-Path -Path "$env:APPDATA" -ChildPath "RustDesk\config\RustDesk.toml"),
                  (Join-Path -Path "$env:ProgramData" -ChildPath "RustDesk\config\RustDesk.toml")
              )

              foreach ($configPath in $rustDeskConfigPaths) {
                  if (Test-Path $configPath) {
                      Write-Host "Prüfe Konfigurationsdatei: $configPath"
                      try {
                          $configContent = Get-Content -Path $configPath -Raw
                          if ($configContent -match "client_id\s*=\s*[`"']?(\d{9})[`"']?") {
                              $rustDeskId = $Matches[1]
                              Write-Host "RustDesk ID in Konfigurationsdatei gefunden: $configPath - ID: $rustDeskId"
                              break
                          } else {
                              Write-Warning "RustDesk ID (client_id = 9 Ziffern) nicht in Konfigurationsdatei gefunden: $configPath"
                          }
                      } catch {
                          Write-Error "Fehler beim Lesen der Konfigurationsdatei $configPath : $($_.Exception.Message)"
                      }
                  } else {
                      Write-Warning "RustDesk-Konfigurationsdatei nicht gefunden unter $configPath"
                  }
              }
          }

          Write-Host "--- Versuch, RustDesk ID abzurufen, beendet ---"

          # Ausgabe der RustDesk ID an den GitHub Actions Workflow Output
          if ($rustDeskId) {
              Write-Host "RustDesk ID erfolgreich abgerufen: $rustDeskId"
              "rustdesk_id=$rustDeskId" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
              Write-Error "FEHLER: RustDesk ID konnte nach mehreren Versuchen nicht abgerufen werden."
              "rustdesk_id=NOT_AVAILABLE" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

          # Alle RustDesk-Prozesse beenden
          Write-Host "Beende alle laufenden RustDesk-Prozesse..."
          Get-Process -Name "rustdesk" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 5
          Write-Host "Alle RustDesk-Prozesse beendet."

      - name: Runner aktiv halten
        # Führe diesen Step nur aus, wenn die ID erfolgreich abgerufen wurde
        if: steps.download_rustdesk_step.outputs.download_success == 'true'
        run: |
          $durationMinutes = [int]"${{ github.event.inputs.duration_minutes }}"
          if ($durationMinutes -gt 360) {
              $durationMinutes = 360
              Write-Warning "Dauer auf maximal 360 Minuten begrenzt."
          }
          $durationSeconds = $durationMinutes * 60
          Write-Host "Halte den Runner für $durationMinutes Minuten ($durationSeconds Sekunden) aktiv..."
          Write-Host "RustDesk ID: ${{ steps.download_rustdesk_step.outputs.rustdesk_id }}"
          Start-Sleep -Seconds $durationSeconds
